"use client";

import React, { useState, useEffect } from 'react';
import { BookOpen, Sparkles, ArrowLeft, Search, ExternalLink, Maximize2, Minimize2, BookMarked } from 'lucide-react';
import Link from 'next/link';
import TapToTranslateText from '@/components/TapToTranslateText';
import { useUserStore } from '@/store/useUserStore';
import { useAuth } from '@/components/AuthProvider';
import { useRouter } from 'next/navigation';
import { supabase } from '@/lib/supabase';
import storiesData from '@/data/stories.json';

// Dynamic Library fetched from the local JSON generated by the secondary Agent
const MOCK_LIBRARY = storiesData as Array<{id: number, title: string, level: string, language: string, content: string}>;

// --- German Storybook PDF Section ---
function GermanStorybookSection() {
  const [fullscreen, setFullscreen] = useState(false);

  return (
    <div className="mt-12 space-y-6 animate-in fade-in slide-in-from-bottom-6 duration-500">
      {/* Section Header */}
      <div className="flex items-center space-x-4">
        <div className="h-px flex-1 bg-gradient-to-r from-transparent via-amber-500/30 to-transparent" />
        <div className="flex items-center space-x-2 px-4 py-1.5 rounded-full bg-amber-500/10 border border-amber-500/20">
          <BookMarked className="w-4 h-4 text-amber-400" />
          <span className="text-sm font-semibold text-amber-400 tracking-wide">German Storybook Collection</span>
        </div>
        <div className="h-px flex-1 bg-gradient-to-r from-transparent via-amber-500/30 to-transparent" />
      </div>

      {/* Book Card */}
      <div className="rounded-3xl bg-gradient-to-br from-[#1A1500] via-[#141A29] to-[#0B0F19] border border-amber-500/20 shadow-2xl overflow-hidden">
        {/* Card Header */}
        <div className="p-6 md:p-8 border-b border-white/5 flex flex-col md:flex-row md:items-center justify-between gap-4">
          <div className="flex items-start space-x-4">
            {/* Book Icon */}
            <div className="w-14 h-20 bg-gradient-to-b from-amber-400 to-amber-600 rounded-lg shadow-xl flex items-center justify-center flex-shrink-0 relative overflow-hidden">
              <div className="absolute inset-0 bg-gradient-to-br from-white/20 to-transparent" />
              <BookOpen className="w-7 h-7 text-white relative z-10" />
            </div>
            <div className="space-y-1.5">
              <div className="flex items-center space-x-2">
                <span className="px-2.5 py-0.5 bg-amber-500/20 text-amber-400 text-xs font-bold rounded-full border border-amber-500/30">A1 – A2</span>
                <span className="px-2.5 py-0.5 bg-emerald-500/20 text-emerald-400 text-xs font-bold rounded-full border border-emerald-500/30">Beginner Friendly</span>
              </div>
              <h2 className="text-xl md:text-2xl font-extrabold text-slate-100 leading-tight">
                Learn German with Stories: Café in Berlin
              </h2>
              <p className="text-slate-400 text-sm">by André Klein · 10 short stories for beginners</p>
              <p className="text-slate-500 text-xs leading-relaxed max-w-xl">
                Follow Dino through the vibrant streets of Berlin in 10 engaging short stories. Perfect for A1–A2 learners — real German, real situations.
              </p>
            </div>
          </div>

          <div className="flex items-center space-x-2 flex-shrink-0">
            <button
              onClick={() => setFullscreen(f => !f)}
              className="flex items-center space-x-2 px-4 py-2.5 rounded-xl bg-amber-500/10 hover:bg-amber-500/20 border border-amber-500/20 text-amber-400 text-sm font-semibold transition-all duration-200"
            >
              {fullscreen ? <Minimize2 className="w-4 h-4" /> : <Maximize2 className="w-4 h-4" />}
              <span>{fullscreen ? 'Collapse' : 'Expand'}</span>
            </button>
            <a
              href="/learn-german-cafe-berlin.pdf"
              target="_blank"
              rel="noopener noreferrer"
              className="flex items-center space-x-2 px-4 py-2.5 rounded-xl bg-white/5 hover:bg-white/10 border border-white/10 text-slate-300 hover:text-white text-sm font-semibold transition-all duration-200"
            >
              <ExternalLink className="w-4 h-4" />
              <span>Open Tab</span>
            </a>
          </div>
        </div>

        {/* PDF Embed */}
        <div
          className="transition-all duration-500 overflow-hidden"
          style={{ height: fullscreen ? '85vh' : '600px' }}
        >
          <iframe
            src="/learn-german-cafe-berlin.pdf"
            className="w-full h-full"
            title="Learn German with Stories: Café in Berlin"
            style={{ border: 'none', background: '#0B0F19' }}
          />
        </div>

        {/* Footer hint */}
        <div className="px-8 py-3 bg-black/20 border-t border-white/5 text-center">
          <p className="text-xs text-slate-600">Tap words in the stories above to translate them · Use this book for extended reading practice</p>
        </div>
      </div>
    </div>
  );
}

export default function ReadingLibrary() {
  const router = useRouter();
  const { user } = useAuth();
  const { targetLanguage, level: userLevel, hasOnboarded } = useUserStore();
  const [mounted, setMounted] = useState(false);
  
  const [activeStory, setActiveStory] = useState<any>(null);

  useEffect(() => {
    setMounted(true);
  }, []);

  useEffect(() => {
    if (mounted && !hasOnboarded) {
      router.push('/onboarding');
    }
  }, [hasOnboarded, mounted, router]);

  const handleOpenStory = (story: any) => {
    setActiveStory(story);
    if (user) {
      supabase.rpc('increment_stories_read', { target_user_id: user.id })
        .then(({ error }) => {
          if (error) console.error('Failed to increment stories_read:', error.message);
        });
    }
  };

  if (!mounted || !hasOnboarded) return null;

  const stories = MOCK_LIBRARY.filter(s => s.language === targetLanguage);

  if (activeStory) {
    return (
       <div className="min-h-screen bg-[#0B0F19] text-slate-200 p-6 md:p-12 font-sans animate-in fade-in duration-300">
          <div className="max-w-4xl mx-auto space-y-8">
            <button onClick={() => setActiveStory(null)} className="inline-flex items-center space-x-2 text-indigo-400 hover:text-indigo-300 transition-colors font-medium">
              <ArrowLeft className="w-5 h-5" />
              <span>Back to Library</span>
            </button>
            <div className="p-6 md:p-10 rounded-3xl bg-[#141A29] border border-white/5 shadow-2xl">
              <div className="flex items-center justify-between mb-8 pb-6 border-b border-white/10">
                <h1 className="text-3xl md:text-4xl font-extrabold text-slate-100 leading-tight">{activeStory.title}</h1>
                <span className="px-5 py-2 bg-indigo-500/20 text-indigo-400 font-bold rounded-full text-sm border border-indigo-500/30">{activeStory.level}</span>
              </div>
              <TapToTranslateText text={activeStory.content} />
            </div>
          </div>
       </div>
    );
  }

  return (
    <div className="min-h-screen bg-[#0B0F19] text-slate-200 p-6 md:p-12 font-sans animate-in fade-in duration-500">
      <div className="max-w-5xl mx-auto space-y-8">
        <Link href="/" className="inline-flex items-center space-x-2 text-indigo-400 hover:text-indigo-300 transition-colors font-medium">
          <ArrowLeft className="w-5 h-5" />
          <span>Back to Dashboard</span>
        </Link>
        
        <header className="space-y-4">
          <div className="flex flex-col md:flex-row md:items-end justify-between gap-4">
             <div>
                <div className="flex items-center space-x-4 mb-3">
                  <div className="w-12 h-12 bg-blue-500/20 rounded-2xl flex items-center justify-center text-blue-400 shadow-sm border border-blue-500/20">
                    <BookOpen className="w-6 h-6" />
                  </div>
                  <h1 className="text-3xl md:text-4xl font-extrabold tracking-tight text-slate-100">The Library</h1>
                </div>
                <p className="text-slate-400 text-lg">Pick a story to immerse yourself. Your recommended level is <span className="font-bold text-indigo-400 px-2 py-1 bg-indigo-500/20 rounded-lg">{userLevel}</span>.</p>
             </div>
             
             <div className="flex space-x-2">
                <div className="flex items-center space-x-2 bg-[#141A29] px-4 py-3 rounded-xl border border-white/5 shadow-sm">
                  <Search className="w-5 h-5 text-slate-500" />
                  <input type="text" placeholder="Search stories..." className="bg-transparent outline-none text-sm w-36 font-medium text-slate-300 placeholder:text-slate-600" />
                </div>
             </div>
          </div>
        </header>

        {/* Library Feed */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 pt-6">
          {stories.length === 0 ? (
            <div className="col-span-full py-16 text-center text-slate-400 bg-[#141A29] rounded-3xl border border-white/5 shadow-sm">
              <Sparkles className="w-10 h-10 mx-auto text-indigo-500 mb-4" />
              <p className="text-lg">No stories available for <b>{targetLanguage}</b> yet.</p>
              <p className="text-sm mt-2">The AI Content Agent is writing them right now!</p>
            </div>
          ) : (
            stories.map((story) => (
              <div 
                key={story.id}
                onClick={() => handleOpenStory(story)}
                className="bg-[#141A29] p-6 rounded-3xl border border-white/5 shadow-lg hover:shadow-2xl hover:border-indigo-500/30 transition-all cursor-pointer group flex flex-col justify-between h-64 relative overflow-hidden"
              >
                <div className="space-y-4 relative z-10">
                  <div className="flex justify-between items-start">
                    <span className={`px-3 py-1 font-bold rounded-lg text-xs border ${
                      story.level === userLevel 
                        ? 'bg-emerald-500/20 text-emerald-400 border-emerald-500/30'
                        : 'bg-white/5 text-slate-400 border-white/10'
                    }`}>
                      {story.level}
                    </span>
                    {story.level === userLevel && <Sparkles className="w-4 h-4 text-emerald-400" />}
                  </div>
                  <h3 className="text-xl font-bold text-slate-100 line-clamp-2 leading-tight group-hover:text-indigo-400 transition-colors">{story.title}</h3>
                  <p className="text-slate-400 text-sm line-clamp-3 leading-relaxed">{story.content}</p>
                </div>
                <div className="relative z-10 pt-4 flex items-center justify-between text-indigo-400 text-sm font-semibold opacity-0 group-hover:opacity-100 transition-opacity transform translate-y-2 group-hover:translate-y-0 border-t border-white/10 mt-4">
                  <span>Read Story</span>
                  <span>&rarr;</span>
                </div>
              </div>
            ))
          )}
        </div>

        {/* German Storybook — only shown for German learners */}
        {targetLanguage === 'German' && <GermanStorybookSection />}

      </div>
    </div>
  );
}
